// <auto-generated />
using System;
using DispatchSystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DispatchSystem.Api.Migrations
{
    [DbContext(typeof(DispatchDbContext))]
    [Migration("20260805135106_SeedMoreRiders")]
    partial class SeedMoreRiders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DispatchSystem.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DropoffAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RiderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RiderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DispatchSystem.Api.Models.Rider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Riders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAvailable = true,
                            Name = "張飛"
                        },
                        new
                        {
                            Id = 2,
                            IsAvailable = false,
                            Name = "劉備"
                        },
                        new
                        {
                            Id = 3,
                            IsAvailable = false,
                            Name = "關羽"
                        },
                        new
                        {
                            Id = 4,
                            IsAvailable = false,
                            Name = "趙雲"
                        },
                        new
                        {
                            Id = 5,
                            IsAvailable = false,
                            Name = "馬超"
                        },
                        new
                        {
                            Id = 6,
                            IsAvailable = false,
                            Name = "黃忠"
                        },
                        new
                        {
                            Id = 7,
                            IsAvailable = false,
                            Name = "曹操"
                        },
                        new
                        {
                            Id = 8,
                            IsAvailable = false,
                            Name = "孫權"
                        },
                        new
                        {
                            Id = 9,
                            IsAvailable = false,
                            Name = "周瑜"
                        },
                        new
                        {
                            Id = 10,
                            IsAvailable = false,
                            Name = "呂布"
                        });
                });

            modelBuilder.Entity("DispatchSystem.Api.Models.Order", b =>
                {
                    b.HasOne("DispatchSystem.Api.Models.Rider", "Rider")
                        .WithMany("Orders")
                        .HasForeignKey("RiderId");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("DispatchSystem.Api.Models.Rider", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
